name: Java CI/CD with Maven and GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    name: Build & Test (CI)
    runs-on: ubuntu-latest

    steps:
      # 1) Descargar el código
      - uses: actions/checkout@v4

      # 2) Configurar Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3) Compilar y ejecutar tests
      - name: Build with Maven
        run: mvn -B package

  deploy:
    name: Build & Push Docker image (CD)
    runs-on: ubuntu-latest
    needs: build-test   # solo corre si CI pasó

    steps:
      # 1) Descargar el código
      - uses: actions/checkout@v4

      # 2) Login en GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: drac22
          password: ${{ secrets.GHCR_PAT }}
      # 3) Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/drac22/integracion_despliegues:latest
